version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: rundle-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: rundle_dev
      POSTGRES_USER: rundle
      POSTGRES_PASSWORD: rundle_local_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U rundle -d rundle_dev']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
